development:
  # twilio stuff
  #
  # If you don't already have a SID and token
  # go to http://twilio.com and sign up for a demo
  # account.
  TWILIO_SID: 'AC10984a77f9963a1cdb24ccb400112124'
  TWILIO_TKN: '151a5f0578c3b22adc7229727648a04b'
